AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Implementation of the logic for handling passage of the start gate.

Globals:
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: start-gate-passage-detected-${StageName}
      StageName:
        Ref: StageName

  StartGatePassageDetectedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: start-gate-passage-detected-${StageName}
      CodeUri: target/start-gate-passage-detected-lambda-1.0-SNAPSHOT.jar
      Handler: se.caglabs.cloudracing.lambda.startgatepassedlambda.service.StartGatePassedHandler::execute
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: CurrentRaceTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /start-gate-passed
            Method: POST
            RestApiId:
              Ref: RestApi

  CurrentRaceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: current-race-${StageName}
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  RacesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: races-${StageName}
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
