package se.caglabs.cloudracing.lambda.registercontestant.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;


@DynamoDBTable(tableName="registered-users-STAGE")
@Data
public class User {
    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey()
    private String id;
    @DynamoDBAttribute(attributeName="name")
    private String name;
    @DynamoDBAttribute(attributeName="password")
    private String password;
    @DynamoDBAttribute(attributeName="type")
    private String type;
}
