AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Implementation of the logic for registration of contestants.

Globals:
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: cloud-racing-client-api-${StageName}
      StageName:
        Ref: StageName

  RegisterContestantFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: register-contestant-${StageName}
      CodeUri: target/register-contestant-lambda-1.0-SNAPSHOT.jar
      Handler: se.caglabs.cloudracing.lambda.registercontestant.service.RegisterContestantHandler::execute
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: RegisteredUsersTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /registered-users
            Method: POST
            RestApiId:
              Ref: RestApi

  RegisteredUsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: registered-users-${StageName}
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
